apiVersion: v1
kind: ConfigMap
metadata:
  name: prom-exporter-prod
  namespace: infra
data:
  PORT: "8200"
  REDIS_SYNC_INTERVAL: "30"
  REDIS_DSN: "redis-prod-master.infra:6379"
  GIN_MODE: "release"