apiVersion: apps/v1
kind: Deployment
metadata:
  name: prom-exporter-prod
  namespace: infra
  labels:
    app: prom-exporter-prod
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
  selector:
    matchLabels:
      app: prom-exporter-prod
  template:
    metadata:
      namespace: infra
      labels:
        app: prom-exporter-prod
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "9991"
        reloader.stakater.com/auto: "true"

    spec:
      tolerations:
        - key: "node-role"
          operator: "Equal"
          value: "platform-worker"
      containers:
        - name: prom-exporter
          image: cr.yandex/crpesloqeokk24jjth3o/services/prom-exporter:master
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
              name: http-server
            - containerPort: 9991
              name: prometheus
          envFrom:
            - configMapRef:
                name: prom-exporter-prod
          env:
            - name: ENVIRONMENT
              value: "production"
