apiVersion: v1
kind: Service
metadata:
  name: prom-exporter-prod
  namespace: infra
  labels:
    app: prom-exporter-prod
spec:
  type: ClusterIP
  ports:
    - port: 8200
      name: prom-http-server
  selector:
    app: prom-exporter-prod